#!/bin/bash
#
# 增量爬取股票数据脚本 

SCRIPT_PATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
PROJECT_PATH=$(dirname "$SCRIPT_PATH")

cd "$PROJECT_PATH"
source venv/bin/activate
python3 crawl.py >> logs/crawl.log
