#!/bin/bash
#
# es 全量同步脚本

SCRIPT_PATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
PROJECT_PATH=$(dirname "$SCRIPT_PATH")

cd "$PROJECT_PATH"
source venv/bin/activate
python3 es.py >> logs/es.log
