#!/bin/bash
#
# 价格监控脚本

SCRIPT_PATH="$(cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P)"
PROJECT_PATH=$(dirname "$SCRIPT_PATH")

cd "$PROJECT_PATH"
source venv/bin/activate
python3 monitor.py >> logs/monitor.log
